[build]
functions = "netlify/functions" # Directory for serverless functions
publish = "static"              # Directory for static assets
command = "npm install && npm run build" # Build command (if needed)

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200